import { StyleSheet } from "react-native";
import { colors, radius, space } from "./theme";
import { fonts, lbl, meta, lightColors } from "../styles/theme";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    scrollContent: {
        paddingHorizontal: 20,
    },
    header: {
        paddingTop: 20,
        paddingBottom: 24,
    },
    headerTitle: { fontFamily: fonts.displayBold, fontSize: 32, color: lightColors.text,
        marginBottom: 4 },
    headerSubtitle: { fontFamily: fonts.body, fontSize: 16, color: lightColors.textMuted },
    section: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 20,
    },
    sectionTitle: { fontFamily: fonts.displayBold, fontSize: 18, color: lightColors.text },
    inputGroup: {
        marginBottom: 16,
    },
    label: { ...meta(14, "semi"), color: lightColors.textBody,
        marginBottom: 8 },
    optional: { ...meta(13, "regular"), color: lightColors.textLight },
    input: { fontFamily: fonts.body, fontSize: 16, borderWidth: 1.5,
        borderColor: lightColors.border,
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        
        color: lightColors.text,
        backgroundColor: "#fff" },
    textarea: {
        height: 120,
        textAlignVertical: "top",
        paddingTop: 12,
    },
    langSection: {
        marginBottom: 16,
    },
    langSectionTitle: { ...lbl(14, "semi", 0.08), color: lightColors.textMuted,
        marginBottom: 12 },
    langTabs: {
        flexDirection: "row",
        gap: 12,
    },
    langTab: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: lightColors.border,
        alignItems: "center",
    },
    langTabActive: {
        backgroundColor: lightColors.primary,
        borderColor: lightColors.primary,
    },
    langTabText: { ...meta(15, "semi"), color: lightColors.textMuted },
    langTabTextActive: {
        color: "#fff",
    },
    posterContainer: {
        gap: 12,
    },
    posterImage: {
        width: "100%",
        aspectRatio: 3/4,
        borderRadius: 12,
        backgroundColor: "#F3F4F6",
    },
    changePosterBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: lightColors.border,
        backgroundColor: "#fff",
    },
    changePosterText: { ...meta(15, "semi"), color: lightColors.primary },
    uploadBtn: {
        borderWidth: 2,
        borderColor: lightColors.border,
        borderStyle: "dashed",
        borderRadius: 12,
        paddingVertical: 40,
        alignItems: "center",
        gap: 8,
        backgroundColor: "#F9FAFB",
    },
    uploadText: { ...meta(16, "semi"), color: lightColors.textBody },
    uploadSubtext: { ...meta(14, "regular"), color: lightColors.textLight },
    toggleContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        marginTop: 4,
    },
    toggleInfo: {
        flex: 1,
    },
    toggleTitle: { ...meta(15, "semi"), color: lightColors.text,
        marginBottom: 2 },
    toggleSubtitle: { ...meta(13, "regular"), color: lightColors.textMuted },
    toggle: {
        width: 52,
        height: 32,
        borderRadius: 16,
        backgroundColor: lightColors.border,
        padding: 2,
        justifyContent: "center",
    },
    toggleActive: {
        backgroundColor: lightColors.primary,
    },
    toggleKnob: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    toggleKnobActive: {
        alignSelf: "flex-end",
    },
    actions: {
        flexDirection: "row",
        gap: 12,
        marginTop: 8,
    },
    draftBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 12,
        backgroundColor: "#fff",
        borderWidth: 1.5,
        borderColor: lightColors.border,
    },
    draftBtnText: { ...meta(16, "semi"), color: lightColors.textMuted },
    publishBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 12,
        backgroundColor: lightColors.primary,
        elevation: 4,
    },
    publishBtnText: { ...meta(16, "semi"), color: "#fff" },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginBottom: 12,
    },
    tagChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: "#FEE2E2",
        borderWidth: 1,
        borderColor: "#FCA5A5",
        borderRadius: 20,
        paddingVertical: 6,
        paddingLeft: 12,
        paddingRight: 8,
    },
    tagChipText: { ...meta(14, "medium"), color: lightColors.primary },
    tagInputContainer: {
        flexDirection: "row",
        gap: 8,
        alignItems: "center",
    },
    addTagBtn: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: lightColors.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    addTagBtnDisabled: {
        backgroundColor: "#D1D5DB",
    },
    maxTagsNotice: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: "#FEE2E2",
        borderRadius: 8,
        marginTop: 8,
    },
    maxTagsText: { ...meta(13, "medium"), color: lightColors.primary },
});

export default styles;