import { StyleSheet } from "react-native";
import { colors, radius, space } from "./theme";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    scrollContent: {
        paddingHorizontal: 20,
    },
    header: {
        paddingTop: 20,
        paddingBottom: 24,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: "700",
        color: "#111827",
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 16,
        color: "#6B7280",
    },
    section: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#111827",
    },
    inputGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        color: "#374151",
        marginBottom: 8,
    },
    optional: {
        fontSize: 13,
        fontWeight: "400",
        color: "#9CA3AF",
    },
    input: {
        borderWidth: 1.5,
        borderColor: "#E5E7EB",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 16,
        color: "#111827",
        backgroundColor: "#fff",
    },
    textarea: {
        height: 120,
        textAlignVertical: "top",
        paddingTop: 12,
    },
    langSection: {
        marginBottom: 16,
    },
    langSectionTitle: {
        fontSize: 14,
        fontWeight: "600",
        color: "#6B7280",
        marginBottom: 12,
        textTransform: "uppercase",
    },
    langTabs: {
        flexDirection: "row",
        gap: 12,
    },
    langTab: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#E5E7EB",
        alignItems: "center",
    },
    langTabActive: {
        backgroundColor: "#8C0327",
        borderColor: "#8C0327",
    },
    langTabText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#6B7280",
    },
    langTabTextActive: {
        color: "#fff",
    },
    posterContainer: {
        gap: 12,
    },
    posterImage: {
        width: "100%",
        aspectRatio: 3/4,
        borderRadius: 12,
        backgroundColor: "#F3F4F6",
    },
    changePosterBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: "#E5E7EB",
        backgroundColor: "#fff",
    },
    changePosterText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#8C0327",
    },
    uploadBtn: {
        borderWidth: 2,
        borderColor: "#E5E7EB",
        borderStyle: "dashed",
        borderRadius: 12,
        paddingVertical: 40,
        alignItems: "center",
        gap: 8,
        backgroundColor: "#F9FAFB",
    },
    uploadText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#374151",
    },
    uploadSubtext: {
        fontSize: 14,
        color: "#9CA3AF",
    },
    toggleContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        marginTop: 4,
    },
    toggleInfo: {
        flex: 1,
    },
    toggleTitle: {
        fontSize: 15,
        fontWeight: "600",
        color: "#111827",
        marginBottom: 2,
    },
    toggleSubtitle: {
        fontSize: 13,
        color: "#6B7280",
    },
    toggle: {
        width: 52,
        height: 32,
        borderRadius: 16,
        backgroundColor: "#E5E7EB",
        padding: 2,
        justifyContent: "center",
    },
    toggleActive: {
        backgroundColor: "#8C0327",
    },
    toggleKnob: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    toggleKnobActive: {
        alignSelf: "flex-end",
    },
    actions: {
        flexDirection: "row",
        gap: 12,
        marginTop: 8,
    },
    draftBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 12,
        backgroundColor: "#fff",
        borderWidth: 1.5,
        borderColor: "#E5E7EB",
    },
    draftBtnText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#6B7280",
    },
    publishBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 16,
        borderRadius: 12,
        backgroundColor: "#8C0327",
        elevation: 4,
    },
    publishBtnText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#fff",
    },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginBottom: 12,
    },
    tagChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: "#FEE2E2",
        borderWidth: 1,
        borderColor: "#FCA5A5",
        borderRadius: 20,
        paddingVertical: 6,
        paddingLeft: 12,
        paddingRight: 8,
    },
    tagChipText: {
        fontSize: 14,
        fontWeight: "500",
        color: "#8C0327",
    },
    tagInputContainer: {
        flexDirection: "row",
        gap: 8,
        alignItems: "center",
    },
    addTagBtn: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: "#8C0327",
        alignItems: "center",
        justifyContent: "center",
    },
    addTagBtnDisabled: {
        backgroundColor: "#D1D5DB",
    },
    maxTagsNotice: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: "#FEE2E2",
        borderRadius: 8,
        marginTop: 8,
    },
    maxTagsText: {
        fontSize: 13,
        color: "#8C0327",
        fontWeight: "500",
    },
});

export default styles;