import { StyleSheet } from "react-native";
import { fonts, lbl, meta, lightColors, type AppColors } from "./theme";

export const makeFeedStyles = (C: AppColors) => StyleSheet.create({
    feed: { paddingTop: 12, paddingBottom: 28, gap: 11 },

    // ── Card chrome ────────────────────────────────────────────────────────
    // Outfit for headlines and figures, Plus Jakarta Sans for body, meta and UI.
    // lbl() = uppercase chips/kickers/buttons; meta() = sentence-case meta.
    // Weights come from the family name, never fontWeight.
    fcCard: {
        marginHorizontal: 11,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.border,
        borderRadius: 6,
        overflow: "hidden",
        shadowColor: "#1B2233",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 2,
        elevation: 1,
    },
    fcHeader: { flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 17, paddingTop: 15 },
    fcHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 11, flex: 1, minWidth: 0 },
    fcAvatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: C.primaryBg, borderWidth: 1, borderColor: C.border, alignItems: "center", justifyContent: "center", overflow: "hidden" },
    fcAvatarImg: { width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderColor: C.border },
    fcAvatarInitials: { ...lbl(13, "bold", 0.02), color: C.primary },
    fcHeaderText: { flex: 1, minWidth: 0 },
    fcClubName: { fontFamily: fonts.displayBold, fontSize: 15.5, color: C.text },
    fcSubtitle: { ...meta(12.5), color: C.textMuted, marginTop: 2 },
    fcFollowingLabel: { ...lbl(12, "bold", 0.06), color: C.primary },
    fcTypePill: { borderWidth: 1, borderColor: C.border, borderRadius: 3, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: C.bg },
    fcTypePillText: { ...lbl(10, "bold", 0.08), color: C.textMuted },

    fcImageWrap: { position: "relative", backgroundColor: C.skeleton, marginTop: 13 },
    fcImage: { width: "100%", backgroundColor: C.skeleton },
    fcImageEvent: { aspectRatio: 16 / 10 },
    fcImageBanner: { aspectRatio: 21 / 9 },
    fcImageBadgeRow: { position: "absolute", top: 13, left: 15, flexDirection: "row", gap: 6 },
    fcImageBadge: {
        backgroundColor: "rgba(255,255,255,0.94)",
        borderRadius: 4,
        paddingLeft: 8,
        paddingRight: 10,
        paddingVertical: 5,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.18,
        shadowRadius: 3,
        elevation: 2,
    },
    fcImageBadgeText: { ...lbl(11.5, "bold", 0.08), color: C.primary },
    fcDateBadge: {
        position: "absolute",
        right: 15,
        top: 13,
        backgroundColor: C.primary,
        borderRadius: 5,
        paddingHorizontal: 11,
        paddingTop: 6,
        paddingBottom: 7,
        alignItems: "center",
        shadowColor: C.primaryDeep,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.35,
        shadowRadius: 6,
        elevation: 3,
    },
    fcDateMon: { ...lbl(11, "bold", 0.12), color: "#fff" },
    fcDateDay: { fontFamily: fonts.displayBold, fontSize: 25, color: "#fff", lineHeight: 27, marginTop: 1 },

    fcBody: { paddingHorizontal: 17, paddingTop: 15, paddingBottom: 15, gap: 8 },
    // Category kicker above the headline ("Academic · Social").
    fcKicker: { ...lbl(11, "bold", 0.1), color: C.primary },
    fcTitle: { fontFamily: fonts.displayBold, fontSize: 23, color: C.text, letterSpacing: -0.2, lineHeight: 29 },
    fcMeta: { ...meta(13), color: C.textMuted },
    fcMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7 },
    // Keeps a glyph welded to its own label across a wrap.
    fcMetaItem: { flexDirection: "row", alignItems: "center", gap: 7, flexShrink: 1 },
    fcMetaSep: { ...meta(13), color: C.textFaint },
    fcGoingRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    fcGoingAvatar: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: C.surface, overflow: "hidden", backgroundColor: C.primary, alignItems: "center", justifyContent: "center" },
    fcGoingAvatarInit: { ...lbl(9, "bold", 0.02), color: "#fff" },
    fcGoingText: { ...meta(13, "semi"), flex: 1, color: C.text },
    fcGoingTextMuted: { ...meta(13), color: C.textMuted },
    fcMutualRow: { flexDirection: "row", alignItems: "center", gap: 7 },
    fcMutualText: { ...meta(12.5, "semi"), flex: 1, color: C.gold },
    fcDesc: { fontFamily: fonts.body, fontSize: 15.5, color: C.textBody, lineHeight: 23 },
    fcReadMore: { ...meta(13, "bold"), color: C.primary },
    fcContent: { fontFamily: fonts.body, fontSize: 15.5, color: C.textBody, lineHeight: 23 },
    fcTagsRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
    fcTag: { backgroundColor: C.bg, borderWidth: 1, borderColor: C.border, borderRadius: 3, paddingHorizontal: 8, paddingVertical: 4 },
    fcTagText: { ...lbl(10, "bold", 0.08), color: C.textBody },
    // RSVP sits in its own ruled footer rather than inline in the body.
    fcActionFooter: { paddingHorizontal: 17, paddingVertical: 14, marginTop: 4, borderTopWidth: 1, borderTopColor: C.border },
    fcRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        backgroundColor: C.primary,
        borderRadius: 5,
        paddingVertical: 13,
        borderWidth: 1,
        borderColor: C.primary,
        shadowColor: C.primaryDeep,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 2,
    },
    fcRsvpBtnGoing: { backgroundColor: C.surface, borderColor: C.primary, shadowOpacity: 0, elevation: 0 },
    fcRsvpText: { ...lbl(13.5, "bold", 0.06), color: "#fff" },
    fcRsvpTextGoing: { color: C.primary },
    fcRsvpCaption: { ...meta(12.5), color: C.textMuted, marginTop: 9, textAlign: "center" },

    fcActions: { flexDirection: "row", alignItems: "center", gap: 18, paddingHorizontal: 17, paddingVertical: 11, borderTopWidth: 1, borderTopColor: C.border },
    fcAction: { flexDirection: "row", alignItems: "center", gap: 6 },
    fcActionText: { ...meta(14, "bold"), color: C.textMuted },
    fcActionTextActive: { color: C.primary },
    fcActionsSpacer: { flex: 1 },

    // ── Poll ───────────────────────────────────────────────────────────────
    fcPollOptions: { gap: 7, marginTop: 2 },
    fcPollOption: {
        position: "relative",
        borderRadius: 4,
        borderWidth: 1,
        borderColor: C.border,
        backgroundColor: C.surface,
        overflow: "hidden",
        minHeight: 46,
        justifyContent: "center",
    },
    fcPollOptionVoted: { backgroundColor: C.surface },
    fcPollOptionSelected: { borderColor: C.primary, backgroundColor: C.primaryBg, borderLeftWidth: 3 },
    fcPollFill: { position: "absolute", left: 0, top: 0, bottom: 0, backgroundColor: C.track },
    fcPollFillSelected: { backgroundColor: `${C.primary}1A` },
    fcPollOptionContent: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingHorizontal: 15, paddingVertical: 13, zIndex: 1 },
    fcPollOptionLeft: { flexDirection: "row", alignItems: "center", gap: 12, flexShrink: 1 },
    fcPollRadio: { width: 14, height: 14, borderRadius: 7, borderWidth: 1.5, borderColor: C.textFaint, backgroundColor: "transparent" },
    fcPollRadioOn: { borderColor: C.primary, backgroundColor: C.primary, borderWidth: 2.5 },
    fcPollOptionText: { fontFamily: fonts.bodyMedium, fontSize: 15.5, color: C.text, flexShrink: 1 },
    fcPollOptionTextSelected: { fontFamily: fonts.bodySemi, color: C.primary },
    fcPollPct: { fontFamily: fonts.bodyBold, fontSize: 15, color: C.text },
    fcPollPctSelected: { fontFamily: fonts.bodyBold, color: C.primary },
    fcPollMeta: { ...meta(12.5), color: C.textMuted, marginTop: 2 },
    fcPollSubmitRow: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 3 },
    fcPollSubmitBtn: { flex: 1, backgroundColor: C.primary, borderRadius: 4, paddingVertical: 12, alignItems: "center" },
    fcPollSubmitBtnDisabled: { backgroundColor: C.track },
    fcPollSubmitText: { ...lbl(13.5, "bold", 0.06), color: "#fff" },
    fcPollSubmitTextDisabled: { color: C.textMuted },

    // "Vote counted · N votes" summary rule above the results
    fcPollTallyRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingBottom: 9, marginBottom: 3, borderBottomWidth: 1, borderBottomColor: C.border },
    fcPollTallyLabel: { ...meta(12.5, "bold"), color: C.primary },
    fcPollTallyTotal: { fontFamily: fonts.displayBold, fontSize: 18, color: C.text },
    fcPollTallyUnit: { ...meta(12.5), color: C.textMuted },

    // Winner hero — leading option, promoted out of the list
    fcPollWinner: {
        backgroundColor: C.primaryBg,
        borderWidth: 1,
        borderColor: "rgba(142,11,44,0.22)",
        borderLeftWidth: 3,
        borderLeftColor: C.primary,
        borderRadius: 6,
        paddingHorizontal: 15,
        paddingTop: 14,
        paddingBottom: 15,
        marginBottom: 13,
    },
    fcPollWinnerTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 6 },
    fcPollWinnerLabel: { ...lbl(11.5, "bold", 0.1), color: C.primary },
    fcPollWinnerMine: { ...meta(11.5), color: C.primary, opacity: 0.7 },
    fcPollWinnerPct: { fontFamily: fonts.displayBold, fontSize: 36, color: C.primary, lineHeight: 38 },
    fcPollWinnerPctSign: { fontFamily: fonts.displayBold, fontSize: 20, color: C.primary, opacity: 0.55 },
    fcPollWinnerText: { fontFamily: fonts.displayBold, fontSize: 21, color: C.text, lineHeight: 26 },
    fcPollWinnerVotes: { ...meta(12.5), color: C.textMuted, marginTop: 3 },
    fcPollWinnerTrack: { height: 4, backgroundColor: "rgba(142,11,44,0.15)", borderRadius: 2, marginTop: 11, overflow: "hidden" },
    fcPollWinnerFill: { height: "100%", borderRadius: 2, backgroundColor: C.primary },

    // Remaining options, ranked
    fcPollRestLabel: { ...meta(12.5, "semi"), color: C.textMuted, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: C.border },
    fcPollRow: { paddingTop: 11, paddingBottom: 10 },
    fcPollRowTop: { flexDirection: "row", alignItems: "baseline", gap: 12 },
    fcPollRank: { ...meta(13, "bold"), color: C.textMuted, width: 22 },
    fcPollRowText: { flex: 1, fontFamily: fonts.bodyMedium, fontSize: 15.5, color: C.text },
    fcPollRowTextMine: { fontFamily: fonts.bodyBold, color: C.primary },
    fcPollRowMineTag: { ...meta(11, "semi"), color: C.primary },
    fcPollRowPct: { fontFamily: fonts.bodyBold, fontSize: 16, color: C.text },
    fcPollRowPctSign: { fontFamily: fonts.bodyBold, fontSize: 11, color: C.text, opacity: 0.5 },
    fcPollRowTrack: { height: 3, backgroundColor: C.track, marginTop: 8, borderRadius: 2, overflow: "hidden" },
    fcPollRowFill: { height: "100%", borderRadius: 2, backgroundColor: "rgba(27,34,51,0.24)" },
    fcPollRowFillMine: { backgroundColor: "rgba(142,11,44,0.45)" },
    fcPollVotedNote: { ...meta(12.5), color: C.textMuted, paddingTop: 8, paddingBottom: 6 },

    // ── Recap ──────────────────────────────────────────────────────────────
    // Title sits above the hero here (not below it like event cards), so the
    // headline reads before the gallery it introduces.
    fcRecapPill: { borderWidth: 1, borderColor: "rgba(142,11,44,0.25)", borderRadius: 3, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: C.primaryBg },
    fcRecapPillText: { ...lbl(10, "bold", 0.08), color: C.primary },
    fcRecapHeaderRule: { borderBottomWidth: 1, borderBottomColor: C.border, paddingBottom: 15 },
    fcRecapTitle: {
        fontFamily: fonts.displayBold,
        fontSize: 26,
        color: C.text,
        letterSpacing: -0.26,
        lineHeight: 30,
        marginHorizontal: 17,
        marginTop: 16,
        marginBottom: 14,
    },
    fcRecapHero: { height: 250, backgroundColor: C.track, position: "relative" },
    fcRecapArrow: {
        position: "absolute",
        top: "50%",
        marginTop: -17,
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: "rgba(27,34,51,0.45)",
        alignItems: "center",
        justifyContent: "center",
    },
    fcRecapTag: {
        position: "absolute",
        left: 14,
        bottom: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: "rgba(27,34,51,0.55)",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 3,
    },
    fcRecapTagText: { ...lbl(11, "bold", 0.06), color: "#fff" },
    fcRecapCounter: {
        position: "absolute",
        right: 14,
        bottom: 12,
        backgroundColor: "rgba(27,34,51,0.7)",
        paddingHorizontal: 9,
        paddingVertical: 4,
        borderRadius: 3,
    },
    fcRecapCounterText: { ...lbl(11.5, "bold", 0.08), color: "#fff" },
    fcRecapThumbRow: { flexDirection: "row", gap: 8, paddingHorizontal: 17, paddingTop: 10 },
    fcRecapThumb: {
        flex: 1,
        height: 62,
        borderRadius: 4,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: C.border,
        opacity: 0.82,
        backgroundColor: C.track,
    },
    fcRecapThumbOn: { borderWidth: 2, borderColor: C.primary, opacity: 1 },
    fcRecapThumbMore: { alignItems: "center", justifyContent: "center", backgroundColor: C.bg },
    fcRecapThumbMoreText: { ...meta(13, "bold"), color: C.textMuted },
    fcRecapContribRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 17, paddingTop: 14, paddingBottom: 16 },
    fcRecapContribAvatar: {
        width: 26,
        height: 26,
        borderRadius: 13,
        borderWidth: 2,
        borderColor: C.surface,
        overflow: "hidden",
        backgroundColor: C.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    fcRecapContribInit: { ...lbl(9, "bold", 0.02), color: "#fff" },
    fcRecapContribText: { ...meta(13.5), flex: 1, minWidth: 0, color: C.textMuted, lineHeight: 18 },
    fcRecapContribStrong: { fontFamily: fonts.bodyBold, color: C.textBody },
    fcRecapAddBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        // Never let the label squeeze the button out of the card — the names
        // beside it truncate instead.
        flexShrink: 0,
        borderWidth: 1.5,
        borderColor: C.primary,
        borderRadius: 3,
        paddingHorizontal: 12,
        paddingVertical: 9,
    },
    fcRecapAddBtnDone: { backgroundColor: C.primary },
    fcRecapAddBtnText: { ...lbl(12, "bold", 0.06), color: C.primary },
    fcRecapAddBtnTextDone: { color: "#fff" },

    // Rating band — read-only average on the left, your own rating on the right
    fcRecapRating: { flexDirection: "row", alignItems: "center", backgroundColor: C.bg, borderTopWidth: 1, borderTopColor: C.border, paddingHorizontal: 17, paddingVertical: 15 },
    fcRecapAvgRow: { flexDirection: "row", alignItems: "baseline", gap: 9 },
    fcRecapAvg: { fontFamily: fonts.displayBold, fontSize: 34, color: C.text, lineHeight: 34 },
    fcRecapReviews: { ...meta(12.5), color: C.textMuted, marginTop: 5 },
    fcRecapDivider: { width: 1, alignSelf: "stretch", backgroundColor: C.border, marginHorizontal: 18 },
    fcRecapYourLabel: { ...lbl(11, "bold", 0.08), color: C.textMuted, marginBottom: 6 },

    // Empty state — no photos uploaded yet
    fcRecapEmpty: {
        borderWidth: 1.5,
        borderColor: C.border,
        borderStyle: "dashed",
        borderRadius: 6,
        paddingVertical: 22,
        paddingHorizontal: 16,
        alignItems: "center",
        gap: 8,
    },
    fcRecapEmptyTitle: { fontFamily: fonts.displayBold, fontSize: 17, color: C.text, textAlign: "center" },
    fcRecapEmptyBody: { ...meta(13.5), color: C.textMuted, textAlign: "center", marginBottom: 4, lineHeight: 19 },
    fcRecapEmptyBtn: { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: C.primary, borderRadius: 5, paddingHorizontal: 20, paddingVertical: 12 },
    fcRecapEmptyBtnText: { ...lbl(12.5, "bold", 0.06), color: "#fff" },

    // ── Announcement ornament ──────────────────────────────────────────────
    fcAnnRule: { height: 3, backgroundColor: C.primary },
    // fcBody's paddingTop already supplies the space above; marginBottom tops up
    // the parent's 8pt gap to the mockup's 11.
    fcAnnDividerRow: { flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 3 },
    fcAnnDividerLine: { flex: 1, height: 1, backgroundColor: "rgba(142,11,44,0.28)" },
    fcAnnDividerLabel: { ...lbl(12, "bold", 0.12), color: C.primary },
    postCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    postHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 10,
    },
    postHeaderLeft: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        minWidth: 0,
    },
    clubAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: C.primaryBg,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
        overflow: "hidden",
    },
    avatarImage: { width: 38, height: 38, borderRadius: 19 },
    headerText: { flex: 1, minWidth: 0 },
    clubName: { fontSize: 14, fontWeight: "700", color: C.text },
    metaRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 1 },
    postType: {
        fontSize: 11,
        color: C.textLight,
        fontWeight: "600",
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    timestamp: { fontSize: 11, color: C.textLight },

    pollImageWrap: { paddingHorizontal: 14, marginBottom: 10 },

    // Dark poll card — intentionally dark (design choice, not adapted)
    pollCard: { backgroundColor: "#111111" },
    pollCardHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        gap: 10,
    },
    pollCardAvatar: {
        width: 38,
        height: 38,
        borderRadius: 10,
        backgroundColor: C.primary,
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        flexShrink: 0,
    },
    pollCardAvatarImage: { width: 38, height: 38, borderRadius: 10 },
    pollCardHeaderText: { flex: 1 },
    pollCardClubName: {
        fontSize: 13,
        fontWeight: "700",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollCardSubtitle: {
        fontSize: 11,
        fontWeight: "700",
        color: C.primary,
        textTransform: "uppercase",
        letterSpacing: 1,
        marginTop: 1,
    },
    pollCardQuestion: {
        fontSize: 24,
        fontWeight: "800",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        lineHeight: 30,
        paddingHorizontal: 14,
        paddingBottom: 16,
    },
    pollCardImageWrap: { paddingHorizontal: 14, marginBottom: 12 },
    pollCardImage: { width: "100%", height: 200, backgroundColor: "#222" },
    pollCardDescription: {
        fontSize: 13,
        color: "rgba(255,255,255,0.6)",
        paddingHorizontal: 14,
        paddingBottom: 12,
        lineHeight: 19,
    },
    pollCardOptions: { gap: 8, paddingHorizontal: 14, paddingBottom: 4 },
    pollCardOption: {
        position: "relative",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.2)",
        backgroundColor: "rgba(255,255,255,0.05)",
        overflow: "hidden",
        minHeight: 50,
        justifyContent: "center",
    },
    pollCardOptionSelected: { borderColor: C.primary, borderWidth: 0 },
    pollCardProgressBar: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        backgroundColor: "rgba(255,255,255,0.1)",
    },
    pollCardProgressBarSelected: { backgroundColor: C.primary },
    pollCardOptionContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 13,
        zIndex: 1,
    },
    pollCardOptionLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
    pollCardOptionText: {
        fontSize: 12,
        fontWeight: "700",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollCardPercentage: { fontSize: 12, fontWeight: "700", color: "rgba(255,255,255,0.5)" },
    pollCardFooter: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 14,
        gap: 6,
    },
    pollCardFooterText: {
        fontSize: 11,
        fontWeight: "600",
        color: "rgba(255,255,255,0.4)",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },

    // Poll header (light)
    pollHeader: {
        backgroundColor: C.surfaceAlt,
        minHeight: 200,
        justifyContent: "center",
        overflow: "hidden",
    },
    pollGridLines: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: "row",
        justifyContent: "space-around",
    },
    pollGridLine: { width: 1, backgroundColor: "rgba(139,3,39,0.15)" },
    pollHeaderInner: {
        alignItems: "center",
        paddingHorizontal: 24,
        paddingVertical: 36,
        gap: 14,
    },
    pollHeaderTitle: {
        fontFamily: fonts.displayBold,
        fontSize: 38,
        fontStyle: "italic",
        color: C.primary,
        letterSpacing: -0.5,
        textAlign: "center",
        lineHeight: 44,
    },
    pollHeaderDivider: { width: 72, height: 2.5, backgroundColor: C.primary },
    pollHeaderBody: {
        fontSize: 13,
        color: C.text,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.8,
        textAlign: "center",
        lineHeight: 19,
    },

    content: {
        fontSize: 14,
        lineHeight: 21,
        color: C.textBody,
        paddingHorizontal: 14,
        paddingBottom: 12,
    },
    postImage: { width: "100%", height: 220, backgroundColor: C.surfaceAlt },

    // Event preview
    eventPreview: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: C.surfaceAlt,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: C.border,
        marginBottom: 10,
        gap: 10,
    },
    eventIcon: {
        width: 46,
        height: 46,
        backgroundColor: C.border,
        overflow: "hidden",
        flexShrink: 0,
    },
    eventInfo: { flex: 1 },
    eventTitle: { fontSize: 13, fontWeight: "700", color: C.text, marginBottom: 2 },
    eventTime: { fontSize: 12, color: C.textMuted },

    // Light poll options
    pollContainer: { paddingHorizontal: 14, paddingBottom: 4 },
    pollQuestion: { fontSize: 14, fontWeight: "600", color: C.text, marginBottom: 10 },
    pollOptions: { gap: 6, marginBottom: 8 },
    pollOption: {
        position: "relative",
        borderWidth: 1,
        borderColor: C.border,
        backgroundColor: C.surface,
        overflow: "hidden",
        minHeight: 50,
        justifyContent: "center",
    },
    pollOptionVoted: { borderColor: C.border },
    pollOptionSelected: { borderColor: "transparent", borderWidth: 0 },
    pollProgressBar: { position: "absolute", left: 0, top: 0, bottom: 0, backgroundColor: C.border },
    pollProgressBarSelected: { backgroundColor: C.primary },
    pollOptionContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 12,
        zIndex: 1,
    },
    pollOptionLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
    pollOptionText: {
        fontSize: 12,
        fontWeight: "700",
        color: C.textBody,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollOptionTextSelected: { color: "#fff" },
    pollPercentage: { fontSize: 13, fontWeight: "700", color: C.textLight },
    pollPercentageSelected: { color: C.textLight },
    pollDetails: { flexDirection: "row", alignItems: "center", gap: 4, paddingBottom: 8 },
    pollMeta: { fontSize: 12, color: C.textLight },

    // Actions row
    actions: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 11,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
        gap: 18,
    },
    actionButton: { flexDirection: "row", alignItems: "center", gap: 5 },
    actionText: { fontSize: 13, fontWeight: "600", color: C.textLight },
    actionTextActive: { color: C.primary },
    actionsTimestamp: {
        fontSize: 11,
        color: C.textLight,
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },

    // Follow button
    followButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: C.primary,
    },
    followButtonActive: {
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
    },
    followButtonText: {
        fontSize: 12,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    followButtonTextActive: { color: C.textMuted },

    // Event card in feed (poster bg stays dark — image placeholder)
    eventCardImage: { aspectRatio: 1, backgroundColor: "#111", overflow: "hidden" },
    eventCardImagePlaceholder: { ...StyleSheet.absoluteFillObject, backgroundColor: "#2a2a2a" },
    eventCardOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.4)" },
    eventLiveBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    eventLiveBadgeText: {
        fontSize: 10,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 1.5,
        textTransform: "uppercase",
    },
    eventCardContent: { padding: 14, gap: 5, backgroundColor: C.surface },
    eventCardTitle: {
        fontFamily: fonts.displayBold,
        fontSize: 20,
        fontWeight: "700",
        color: C.primary,
        textTransform: "uppercase",
        letterSpacing: 0.3,
        marginBottom: 2,
    },
    eventCardDesc: { fontSize: 13, color: C.textMuted, lineHeight: 19, marginBottom: 4 },
    eventCardMeta: {
        borderLeftWidth: 2,
        borderLeftColor: C.primary,
        paddingLeft: 10,
        paddingVertical: 6,
        backgroundColor: C.bg,
        gap: 5,
        marginBottom: 4,
    },
    eventCardMetaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    eventCardMetaText: {
        fontSize: 11,
        fontWeight: "700",
        color: C.textBody,
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    eventCardButtons: { flexDirection: "row", gap: 8, marginTop: 6 },
    eventCardBtnOutline: {
        flex: 1,
        paddingVertical: 9,
        borderWidth: 1.5,
        borderColor: C.textBody,
        alignItems: "center",
        backgroundColor: C.surfaceAlt,
    },
    eventCardBtnOutlineText: {
        fontSize: 11,
        fontWeight: "700",
        color: C.textBody,
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    eventCardRsvpBtn: { flex: 1 },
    eventCardBtnFilled: {
        paddingVertical: 9,
        backgroundColor: C.primary,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        gap: 5,
        borderWidth: 1.5,
        borderColor: "transparent",
    },
    eventCardBtnFilledText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 1,
        textTransform: "uppercase",
    },

    // Event feed card
    eventFeedCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    eventFeedImageWrap: { position: "relative" },
    eventFeedPoster: { width: "100%", aspectRatio: 1, backgroundColor: "#1a1a1a" },
    eventFeedPosterPlaceholder: { width: "100%", aspectRatio: 1, backgroundColor: "#2a2a2a" },
    eventFeedBody: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 12, gap: 6 },
    eventFeedTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: C.text,
        lineHeight: 26,
        letterSpacing: -0.3,
    },
    eventFeedMetaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    eventFeedMetaText: { fontSize: 13, color: C.textMuted, flex: 1 },
    eventFeedDesc: { fontSize: 13, color: C.textMuted, lineHeight: 20, marginTop: 2 },
    eventFeedDivider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: C.borderWarm,
        marginTop: 6,
        marginBottom: 2,
    },
    eventFeedActions: { flexDirection: "row", alignItems: "center", gap: 10 },
    eventFeedRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    eventFeedRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    eventFeedRsvpText: {
        fontSize: 10,
        fontWeight: "800",
        color: "#fff",
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    eventFeedRsvpTextGoing: { color: C.primary },
    eventFeedHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    eventFeedClubRow: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1, minWidth: 0 },
    eventFeedAvatar: { width: 32, height: 32, borderRadius: 16, overflow: "hidden" },
    eventFeedAvatarPlaceholder: { backgroundColor: C.primaryBg, alignItems: "center", justifyContent: "center" },
    eventFeedClubName: { fontSize: 13, fontWeight: "700", color: C.text, flex: 1 },
    eventFeedFooter: { flexDirection: "row", justifyContent: "flex-end" },

    // New event feed card
    evCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    evBanner: { height: 210, position: "relative", overflow: "hidden", backgroundColor: "#111" },
    evBannerImage: { width: "100%", height: "100%" },
    evBannerTop: {
        position: "absolute",
        top: 12,
        left: 14,
        right: 14,
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
    },
    evTypeLabel: { fontSize: 10, fontWeight: "800", color: "rgba(255,255,255,0.6)", letterSpacing: 2 },
    evDateBadge: {
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: "center",
        minWidth: 42,
    },
    evDateDay: { fontSize: 22, fontWeight: "900", color: "#fff", lineHeight: 24 },
    evDateMon: { fontSize: 10, fontWeight: "800", color: "rgba(255,255,255,0.85)", letterSpacing: 1 },
    evFollowBadge: {
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.35,
        shadowRadius: 4,
        elevation: 4,
    },
    evFollowBadgeText: { fontSize: 11, fontWeight: "800", color: "#fff", letterSpacing: 1.5 },
    evBannerBottom: { position: "absolute", bottom: 14, left: 14, right: 14, gap: 8 },
    evClubChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
        backgroundColor: "rgba(0,0,0,0.55)",
        alignSelf: "flex-start",
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    evClubChipAvatar: { width: 22, height: 22, borderRadius: 2, overflow: "hidden" },
    evClubChipAvatarFallback: { backgroundColor: C.primary, alignItems: "center", justifyContent: "center" },
    evClubChipInitials: { fontSize: 9, fontWeight: "900", color: "#fff", letterSpacing: 0.5 },
    evClubChipName: { fontSize: 11, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    evBannerTitle: { fontSize: 26, fontWeight: "900", color: "#fff", letterSpacing: -0.5, lineHeight: 30 },
    evBody: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 12, gap: 8 },
    evMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 4 },
    evMetaItem: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 1 },
    evMetaSep: { width: 1, height: 12, backgroundColor: C.border, marginHorizontal: 4 },
    evMetaText: { fontSize: 13, color: C.textMuted, flexShrink: 1 },
    evDesc: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    evTagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    evTag: { borderWidth: 1, borderColor: C.border, paddingHorizontal: 8, paddingVertical: 4 },
    evTagText: { fontSize: 10, fontWeight: "800", color: C.textBody, letterSpacing: 0.8 },
    evFooter: { flexDirection: "row", alignItems: "center", gap: 10, paddingTop: 2 },
    evAvatarRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    evGoingText: { fontSize: 12, fontWeight: "700", color: C.textBody, marginLeft: 4 },
    evSpotsLeftBadge: { flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: "#FEF3C7", borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 },
    evSpotsLeftText: { fontSize: 11, fontWeight: "700", color: "#B45309" },
    evSpotsFullBadge: { backgroundColor: "#FEE2E2" },
    evSpotsFullText: { fontSize: 11, fontWeight: "700", color: "#B91C1C" },
    reasonChipRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 8, gap: 8 },
    reasonChip: { flexDirection: "row", alignItems: "center", gap: 5, flexShrink: 1 },
    reasonChipText: { fontSize: 12, fontWeight: "600", color: C.textMuted, flexShrink: 1 },
    showLessText: { fontSize: 12, fontWeight: "600", color: C.textLight },
    evRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    evRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    evRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    evRsvpTextGoing: { color: C.primary },

    poll: {},

    // Hero card (dark bg — image overlay, intentional)
    heroCard: { marginHorizontal: 14, backgroundColor: "#111", overflow: "hidden" },
    heroImageWrap: { height: 280, position: "relative" },
    heroImagePlaceholder: { ...StyleSheet.absoluteFillObject, backgroundColor: "#2a2a2a" },
    heroOverlay: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    heroTypeBadge: {
        position: "absolute",
        top: 12,
        left: 12,
        backgroundColor: C.primary,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    heroTypeBadgeText: { fontSize: 9, fontWeight: "800", color: "#fff", letterSpacing: 1.5, textTransform: "uppercase" },
    heroContent: { position: "absolute", bottom: 0, left: 0, right: 0, padding: 14, gap: 6 },
    heroHeadline: {
        fontSize: 22,
        fontWeight: "900",
        color: "#fff",
        lineHeight: 27,
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },
    heroExcerpt: { fontSize: 13, color: "rgba(255,255,255,0.72)", lineHeight: 18 },
    heroRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 7,
        alignSelf: "flex-start",
    },
    heroRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: "rgba(255,255,255,0.5)" },
    heroRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1, textTransform: "uppercase" },
    heroStats: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 2 },
    heroStatText: { fontSize: 10, fontWeight: "600", color: "rgba(255,255,255,0.65)", letterSpacing: 0.5, textTransform: "uppercase" },
    heroStatDot: { fontSize: 10, color: "rgba(255,255,255,0.4)" },
    heroClubRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: "#1a1a1a",
    },
    heroClubAvatar: { width: 24, height: 24, borderRadius: 12, overflow: "hidden" },
    heroClubAvatarPlaceholder: { backgroundColor: C.primaryBg, alignItems: "center", justifyContent: "center" },
    heroClubName: { fontSize: 11, fontWeight: "700", color: "rgba(255,255,255,0.65)", textTransform: "uppercase", letterSpacing: 0.8 },

    // Text article card
    articleCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
    },
    cardBody: { paddingHorizontal: 16, paddingBottom: 14, gap: 6 },
    articleTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 2 },
    articleCategory: { fontSize: 10, fontWeight: "800", color: C.primary, letterSpacing: 1.5, textTransform: "uppercase" },
    articleHeadline: {
        fontSize: 18,
        fontWeight: "900",
        color: C.text,
        lineHeight: 23,
        textTransform: "uppercase",
        letterSpacing: 0.2,
    },
    articleExcerpt: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    articleByline: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 8,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    articleByText: { fontSize: 10, fontWeight: "700", color: C.textLight, letterSpacing: 0.8, textTransform: "uppercase" },
    articleByRight: { flexDirection: "row", alignItems: "center", gap: 14 },
    articleAction: { flexDirection: "row", alignItems: "center", gap: 4 },
    articleActionText: { fontSize: 12, fontWeight: "600", color: C.textLight },
    articleActionTextActive: { color: C.primary },
    articleByTime: { fontSize: 10, color: C.textLight, textTransform: "uppercase", letterSpacing: 0.5 },

    pollCardByline: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(255,255,255,0.15)",
    },
    pollCardByTime: { fontSize: 10, color: "rgba(255,255,255,0.45)", textTransform: "uppercase", letterSpacing: 0.5 },
    doubleTapHeart: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        alignItems: "center",
        justifyContent: "center",
    },

    // Image article card
    imgArticleCard: { backgroundColor: C.surface, overflow: "hidden", borderBottomWidth: 1, borderBottomColor: C.borderWarm },
    imgArticleImage: { width: "100%", aspectRatio: 1, backgroundColor: C.borderWarm },
    imgArticleBody: { padding: 16, paddingTop: 14, gap: 5 },
    imgArticleCategory: { fontSize: 10, fontWeight: "800", color: C.primary, letterSpacing: 1.5, textTransform: "uppercase" },
    imgArticleHeadline: {
        fontSize: 20,
        fontWeight: "900",
        color: C.text,
        lineHeight: 25,
        textTransform: "uppercase",
        letterSpacing: 0.2,
    },
    imgArticleExcerpt: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    imgArticleActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        marginTop: 8,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    imgArticleRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    imgArticleRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    imgArticleRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1, textTransform: "uppercase" },
    imgArticleRsvpTextGoing: { color: C.primary },
    imgArticleSaveBtn: { flexDirection: "row", alignItems: "center", gap: 5 },
    imgArticleActionText: { fontSize: 10, fontWeight: "700", color: C.textLight, letterSpacing: 0.8, textTransform: "uppercase" },

    // ── Announcement card ──────────────────────────────────────────────────
    announcementCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    announcementInner: {
        flexDirection: "row",
    },
    announcementBorder: {
        width: 3,
        backgroundColor: C.primary,
    },
    announcementContent: {
        flex: 1,
        padding: 16,
        paddingTop: 14,
        gap: 6,
    },
    announcementHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 8,
    },
    announcementClubName: {
        fontSize: 13,
        fontWeight: "700",
        color: C.text,
    },
    announcementTypePill: {
        alignSelf: "flex-start",
        backgroundColor: C.primaryBg,
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 3,
        marginTop: 3,
    },
    announcementTypePillText: {
        fontSize: 9,
        fontWeight: "800",
        color: C.primary,
        letterSpacing: 1.2,
        textTransform: "uppercase",
    },
    announcementTimestamp: {
        fontSize: 10,
        color: C.textLight,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    announcementTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: C.text,
        lineHeight: 23,
        letterSpacing: -0.2,
    },
    announcementExcerpt: {
        fontSize: 13,
        color: C.textMuted,
        lineHeight: 20,
    },
    announcementImage: {
        width: "100%",
        height: 200,
        backgroundColor: C.borderWarm,
    },
    announcementActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 18,
        paddingHorizontal: 16,
        paddingVertical: 11,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    announcementActionBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    announcementActionText: {
        fontSize: 12,
        fontWeight: "600",
        color: C.textLight,
    },
    announcementActionTextActive: { color: C.primary },
    announcementActionSpacer: { flex: 1 },

    multiImgPill: {
        position: "absolute",
        bottom: 8,
        right: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        backgroundColor: "rgba(0,0,0,0.55)",
        paddingHorizontal: 7,
        paddingVertical: 4,
        borderRadius: 4,
    },
    multiImgPillText: { fontSize: 11, fontWeight: "700", color: "#fff" },
});

export const styles = makeFeedStyles(lightColors);
