import { StyleSheet } from "react-native";
import type { AppColors } from "./theme";

export const makeFeedStyles = (C: AppColors) => StyleSheet.create({
    feed: { paddingTop: 12, paddingBottom: 28, gap: 16 },

    // ── Redesigned card chrome (rounded floating cards) ────────────────────
    fcCard: {
        marginHorizontal: 14,
        backgroundColor: C.surface,
        borderWidth: 1,
        borderColor: C.borderWarm,
        overflow: "hidden",
    },
    fcHeader: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, paddingVertical: 12 },
    fcHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, minWidth: 0 },
    fcAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: C.primaryBg, alignItems: "center", justifyContent: "center", overflow: "hidden" },
    fcAvatarImg: { width: 40, height: 40, borderRadius: 20 },
    fcAvatarInitials: { fontSize: 13, fontWeight: "900", color: C.primary, letterSpacing: 0.5 },
    fcHeaderText: { flex: 1, minWidth: 0 },
    fcClubName: { fontSize: 15, fontWeight: "800", color: C.text, letterSpacing: -0.2 },
    fcSubtitle: { fontSize: 12.5, color: C.textLight, marginTop: 1 },
    fcFollowingLabel: { fontSize: 13, fontWeight: "800", color: C.primary },
    fcTypePill: { borderWidth: 1, borderColor: C.gold, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4, backgroundColor: C.surfaceWarm },
    fcTypePillText: { fontSize: 9, fontWeight: "800", color: C.gold, letterSpacing: 1.2 },

    fcImageWrap: { position: "relative", backgroundColor: C.skeleton },
    fcImage: { width: "100%", backgroundColor: C.skeleton },
    fcImageEvent: { aspectRatio: 16 / 10 },
    fcImageBanner: { aspectRatio: 21 / 9 },
    fcImageBadgeRow: { position: "absolute", top: 12, left: 12, flexDirection: "row", gap: 6 },
    fcImageBadge: { backgroundColor: C.gold, borderRadius: 7, paddingHorizontal: 9, paddingVertical: 5, flexDirection: "row", alignItems: "center", gap: 4 },
    fcImageBadgeText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    fcDateBadge: {
        position: "absolute",
        right: 12,
        top: 12,
        backgroundColor: C.primary,
        paddingHorizontal: 11,
        paddingVertical: 7,
        alignItems: "center",
    },
    fcDateMon: { fontSize: 10, fontWeight: "900", color: "#fff", letterSpacing: 1.5 },
    fcDateDay: { fontSize: 18, fontWeight: "900", color: "#fff", lineHeight: 21 },

    fcBody: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 14, gap: 8 },
    fcTitle: { fontSize: 18, fontWeight: "800", color: C.text, letterSpacing: -0.4, lineHeight: 23 },
    fcMeta: { fontSize: 13, color: C.textMuted },
    fcDesc: { fontSize: 14, color: C.textMuted, lineHeight: 20 },
    fcContent: { fontSize: 15, color: C.textBody, lineHeight: 22 },
    fcTagsRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
    fcTag: { backgroundColor: C.primaryBg, borderRadius: 7, paddingHorizontal: 10, paddingVertical: 5 },
    fcTagText: { fontSize: 10, fontWeight: "800", color: C.primary, letterSpacing: 0.8 },
    fcRsvpBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: C.primary, borderRadius: 0, paddingVertical: 13, marginTop: 4 },
    fcRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    fcRsvpText: { fontSize: 13, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    fcRsvpTextGoing: { color: C.primary },

    fcActions: { flexDirection: "row", alignItems: "center", gap: 18, paddingHorizontal: 14, paddingVertical: 11, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: C.borderWarm },
    fcAction: { flexDirection: "row", alignItems: "center", gap: 5 },
    fcActionText: { fontSize: 13, fontWeight: "700", color: C.textMuted },
    fcActionTextActive: { color: C.primary },
    fcActionsSpacer: { flex: 1 },

    // Poll (light redesign)
    fcPollOptions: { gap: 8, marginTop: 2 },
    fcPollOption: { position: "relative", borderRadius: 10, borderWidth: 1.5, borderColor: C.border, backgroundColor: C.surface, overflow: "hidden", minHeight: 46, justifyContent: "center" },
    fcPollOptionVoted: { borderWidth: 0, backgroundColor: C.bg },
    fcPollOptionSelected: { borderWidth: 1.5, borderColor: C.primary, backgroundColor: C.primaryBg },
    fcPollFill: { position: "absolute", left: 0, top: 0, bottom: 0, backgroundColor: C.skeleton },
    fcPollFillSelected: { backgroundColor: `${C.primary}1A` },
    fcPollOptionContent: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingHorizontal: 14, paddingVertical: 12, zIndex: 1 },
    fcPollOptionLeft: { flexDirection: "row", alignItems: "center", gap: 7, flexShrink: 1 },
    fcPollOptionText: { fontSize: 14, fontWeight: "600", color: C.text, flexShrink: 1 },
    fcPollOptionTextSelected: { color: C.primary, fontWeight: "800" },
    fcPollPct: { fontSize: 14, fontWeight: "800", color: C.text },
    fcPollPctSelected: { color: C.primary },
    fcPollMeta: { fontSize: 12.5, color: C.textLight, marginTop: 2 },
    postCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    postHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 10,
    },
    postHeaderLeft: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        minWidth: 0,
    },
    clubAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: C.primaryBg,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 10,
        overflow: "hidden",
    },
    avatarImage: { width: 38, height: 38, borderRadius: 19 },
    headerText: { flex: 1, minWidth: 0 },
    clubName: { fontSize: 14, fontWeight: "700", color: C.text },
    metaRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 1 },
    postType: {
        fontSize: 11,
        color: C.textLight,
        fontWeight: "600",
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    timestamp: { fontSize: 11, color: C.textLight },

    pollImageWrap: { paddingHorizontal: 14, marginBottom: 10 },

    // Dark poll card — intentionally dark (design choice, not adapted)
    pollCard: { backgroundColor: "#111111" },
    pollCardHeader: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        gap: 10,
    },
    pollCardAvatar: {
        width: 38,
        height: 38,
        borderRadius: 10,
        backgroundColor: C.primary,
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        flexShrink: 0,
    },
    pollCardAvatarImage: { width: 38, height: 38, borderRadius: 10 },
    pollCardHeaderText: { flex: 1 },
    pollCardClubName: {
        fontSize: 13,
        fontWeight: "700",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollCardSubtitle: {
        fontSize: 11,
        fontWeight: "700",
        color: C.primary,
        textTransform: "uppercase",
        letterSpacing: 1,
        marginTop: 1,
    },
    pollCardQuestion: {
        fontSize: 24,
        fontWeight: "800",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        lineHeight: 30,
        paddingHorizontal: 14,
        paddingBottom: 16,
    },
    pollCardImageWrap: { paddingHorizontal: 14, marginBottom: 12 },
    pollCardImage: { width: "100%", height: 200, backgroundColor: "#222" },
    pollCardDescription: {
        fontSize: 13,
        color: "rgba(255,255,255,0.6)",
        paddingHorizontal: 14,
        paddingBottom: 12,
        lineHeight: 19,
    },
    pollCardOptions: { gap: 8, paddingHorizontal: 14, paddingBottom: 4 },
    pollCardOption: {
        position: "relative",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.2)",
        backgroundColor: "rgba(255,255,255,0.05)",
        overflow: "hidden",
        minHeight: 50,
        justifyContent: "center",
    },
    pollCardOptionSelected: { borderColor: C.primary, borderWidth: 0 },
    pollCardProgressBar: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        backgroundColor: "rgba(255,255,255,0.1)",
    },
    pollCardProgressBarSelected: { backgroundColor: C.primary },
    pollCardOptionContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 13,
        zIndex: 1,
    },
    pollCardOptionLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
    pollCardOptionText: {
        fontSize: 12,
        fontWeight: "700",
        color: "#fff",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollCardPercentage: { fontSize: 12, fontWeight: "700", color: "rgba(255,255,255,0.5)" },
    pollCardFooter: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 14,
        gap: 6,
    },
    pollCardFooterText: {
        fontSize: 11,
        fontWeight: "600",
        color: "rgba(255,255,255,0.4)",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },

    // Poll header (light)
    pollHeader: {
        backgroundColor: C.surfaceAlt,
        minHeight: 200,
        justifyContent: "center",
        overflow: "hidden",
    },
    pollGridLines: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: "row",
        justifyContent: "space-around",
    },
    pollGridLine: { width: 1, backgroundColor: "rgba(139,3,39,0.15)" },
    pollHeaderInner: {
        alignItems: "center",
        paddingHorizontal: 24,
        paddingVertical: 36,
        gap: 14,
    },
    pollHeaderTitle: {
        fontFamily: "Georgia",
        fontSize: 38,
        fontStyle: "italic",
        color: C.primary,
        letterSpacing: -0.5,
        textAlign: "center",
        lineHeight: 44,
    },
    pollHeaderDivider: { width: 72, height: 2.5, backgroundColor: C.primary },
    pollHeaderBody: {
        fontSize: 13,
        color: C.text,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.8,
        textAlign: "center",
        lineHeight: 19,
    },

    content: {
        fontSize: 14,
        lineHeight: 21,
        color: C.textBody,
        paddingHorizontal: 14,
        paddingBottom: 12,
    },
    postImage: { width: "100%", height: 220, backgroundColor: C.surfaceAlt },

    // Event preview
    eventPreview: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: C.surfaceAlt,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: C.border,
        marginBottom: 10,
        gap: 10,
    },
    eventIcon: {
        width: 46,
        height: 46,
        backgroundColor: C.border,
        overflow: "hidden",
        flexShrink: 0,
    },
    eventInfo: { flex: 1 },
    eventTitle: { fontSize: 13, fontWeight: "700", color: C.text, marginBottom: 2 },
    eventTime: { fontSize: 12, color: C.textMuted },

    // Light poll options
    pollContainer: { paddingHorizontal: 14, paddingBottom: 4 },
    pollQuestion: { fontSize: 14, fontWeight: "600", color: C.text, marginBottom: 10 },
    pollOptions: { gap: 6, marginBottom: 8 },
    pollOption: {
        position: "relative",
        borderWidth: 1,
        borderColor: C.border,
        backgroundColor: C.surface,
        overflow: "hidden",
        minHeight: 50,
        justifyContent: "center",
    },
    pollOptionVoted: { borderColor: C.border },
    pollOptionSelected: { borderColor: "transparent", borderWidth: 0 },
    pollProgressBar: { position: "absolute", left: 0, top: 0, bottom: 0, backgroundColor: C.border },
    pollProgressBarSelected: { backgroundColor: C.primary },
    pollOptionContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 12,
        zIndex: 1,
    },
    pollOptionLeft: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1 },
    pollOptionText: {
        fontSize: 12,
        fontWeight: "700",
        color: C.textBody,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    pollOptionTextSelected: { color: "#fff" },
    pollPercentage: { fontSize: 13, fontWeight: "700", color: C.textLight },
    pollPercentageSelected: { color: C.textLight },
    pollDetails: { flexDirection: "row", alignItems: "center", gap: 4, paddingBottom: 8 },
    pollMeta: { fontSize: 12, color: C.textLight },

    // Actions row
    actions: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 11,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
        gap: 18,
    },
    actionButton: { flexDirection: "row", alignItems: "center", gap: 5 },
    actionText: { fontSize: 13, fontWeight: "600", color: C.textLight },
    actionTextActive: { color: C.primary },
    actionsTimestamp: {
        fontSize: 11,
        color: C.textLight,
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },

    // Follow button
    followButton: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: C.primary,
    },
    followButtonActive: {
        backgroundColor: C.surface,
        borderWidth: 1.5,
        borderColor: C.border,
    },
    followButtonText: {
        fontSize: 12,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    followButtonTextActive: { color: C.textMuted },

    // Event card in feed (poster bg stays dark — image placeholder)
    eventCardImage: { aspectRatio: 1, backgroundColor: "#111", overflow: "hidden" },
    eventCardImagePlaceholder: { ...StyleSheet.absoluteFillObject, backgroundColor: "#2a2a2a" },
    eventCardOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.4)" },
    eventLiveBadge: {
        position: "absolute",
        top: 12,
        right: 12,
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 4,
    },
    eventLiveBadgeText: {
        fontSize: 10,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 1.5,
        textTransform: "uppercase",
    },
    eventCardContent: { padding: 14, gap: 5, backgroundColor: C.surface },
    eventCardTitle: {
        fontFamily: "Georgia",
        fontSize: 20,
        fontWeight: "700",
        color: C.primary,
        textTransform: "uppercase",
        letterSpacing: 0.3,
        marginBottom: 2,
    },
    eventCardDesc: { fontSize: 13, color: C.textMuted, lineHeight: 19, marginBottom: 4 },
    eventCardMeta: {
        borderLeftWidth: 2,
        borderLeftColor: C.primary,
        paddingLeft: 10,
        paddingVertical: 6,
        backgroundColor: C.bg,
        gap: 5,
        marginBottom: 4,
    },
    eventCardMetaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    eventCardMetaText: {
        fontSize: 11,
        fontWeight: "700",
        color: C.textBody,
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    eventCardButtons: { flexDirection: "row", gap: 8, marginTop: 6 },
    eventCardBtnOutline: {
        flex: 1,
        paddingVertical: 9,
        borderWidth: 1.5,
        borderColor: C.textBody,
        alignItems: "center",
        backgroundColor: C.surfaceAlt,
    },
    eventCardBtnOutlineText: {
        fontSize: 11,
        fontWeight: "700",
        color: C.textBody,
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    eventCardRsvpBtn: { flex: 1 },
    eventCardBtnFilled: {
        paddingVertical: 9,
        backgroundColor: C.primary,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        gap: 5,
        borderWidth: 1.5,
        borderColor: "transparent",
    },
    eventCardBtnFilledText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 1,
        textTransform: "uppercase",
    },

    // Event feed card
    eventFeedCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    eventFeedImageWrap: { position: "relative" },
    eventFeedPoster: { width: "100%", aspectRatio: 1, backgroundColor: "#1a1a1a" },
    eventFeedPosterPlaceholder: { width: "100%", aspectRatio: 1, backgroundColor: "#2a2a2a" },
    eventFeedBody: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 12, gap: 6 },
    eventFeedTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: C.text,
        lineHeight: 26,
        letterSpacing: -0.3,
    },
    eventFeedMetaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    eventFeedMetaText: { fontSize: 13, color: C.textMuted, flex: 1 },
    eventFeedDesc: { fontSize: 13, color: C.textMuted, lineHeight: 20, marginTop: 2 },
    eventFeedDivider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: C.borderWarm,
        marginTop: 6,
        marginBottom: 2,
    },
    eventFeedActions: { flexDirection: "row", alignItems: "center", gap: 10 },
    eventFeedRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    eventFeedRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    eventFeedRsvpText: {
        fontSize: 10,
        fontWeight: "800",
        color: "#fff",
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    eventFeedRsvpTextGoing: { color: C.primary },
    eventFeedHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    eventFeedClubRow: { flexDirection: "row", alignItems: "center", gap: 8, flex: 1, minWidth: 0 },
    eventFeedAvatar: { width: 32, height: 32, borderRadius: 16, overflow: "hidden" },
    eventFeedAvatarPlaceholder: { backgroundColor: C.primaryBg, alignItems: "center", justifyContent: "center" },
    eventFeedClubName: { fontSize: 13, fontWeight: "700", color: C.text, flex: 1 },
    eventFeedFooter: { flexDirection: "row", justifyContent: "flex-end" },

    // New event feed card
    evCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    evBanner: { height: 210, position: "relative", overflow: "hidden", backgroundColor: "#111" },
    evBannerImage: { width: "100%", height: "100%" },
    evBannerTop: {
        position: "absolute",
        top: 12,
        left: 14,
        right: 14,
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
    },
    evTypeLabel: { fontSize: 10, fontWeight: "800", color: "rgba(255,255,255,0.6)", letterSpacing: 2 },
    evDateBadge: {
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: "center",
        minWidth: 42,
    },
    evDateDay: { fontSize: 22, fontWeight: "900", color: "#fff", lineHeight: 24 },
    evDateMon: { fontSize: 10, fontWeight: "800", color: "rgba(255,255,255,0.85)", letterSpacing: 1 },
    evFollowBadge: {
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.35,
        shadowRadius: 4,
        elevation: 4,
    },
    evFollowBadgeText: { fontSize: 11, fontWeight: "800", color: "#fff", letterSpacing: 1.5 },
    evBannerBottom: { position: "absolute", bottom: 14, left: 14, right: 14, gap: 8 },
    evClubChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
        backgroundColor: "rgba(0,0,0,0.55)",
        alignSelf: "flex-start",
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    evClubChipAvatar: { width: 22, height: 22, borderRadius: 2, overflow: "hidden" },
    evClubChipAvatarFallback: { backgroundColor: C.primary, alignItems: "center", justifyContent: "center" },
    evClubChipInitials: { fontSize: 9, fontWeight: "900", color: "#fff", letterSpacing: 0.5 },
    evClubChipName: { fontSize: 11, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    evBannerTitle: { fontSize: 26, fontWeight: "900", color: "#fff", letterSpacing: -0.5, lineHeight: 30 },
    evBody: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 12, gap: 8 },
    evMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 4 },
    evMetaItem: { flexDirection: "row", alignItems: "center", gap: 4, flexShrink: 1 },
    evMetaSep: { width: 1, height: 12, backgroundColor: C.border, marginHorizontal: 4 },
    evMetaText: { fontSize: 13, color: C.textMuted, flexShrink: 1 },
    evDesc: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    evTagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    evTag: { borderWidth: 1, borderColor: C.border, paddingHorizontal: 8, paddingVertical: 4 },
    evTagText: { fontSize: 10, fontWeight: "800", color: C.textBody, letterSpacing: 0.8 },
    evFooter: { flexDirection: "row", alignItems: "center", gap: 10, paddingTop: 2 },
    evAvatarRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    evGoingText: { fontSize: 12, fontWeight: "700", color: C.textBody, marginLeft: 4 },
    evSpotsLeftBadge: { flexDirection: "row", alignItems: "center", gap: 3, backgroundColor: "#FEF3C7", borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 },
    evSpotsLeftText: { fontSize: 11, fontWeight: "700", color: "#B45309" },
    evSpotsFullBadge: { backgroundColor: "#FEE2E2" },
    evSpotsFullText: { fontSize: 11, fontWeight: "700", color: "#B91C1C" },
    reasonChipRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingBottom: 8, gap: 8 },
    reasonChip: { flexDirection: "row", alignItems: "center", gap: 5, flexShrink: 1 },
    reasonChipText: { fontSize: 12, fontWeight: "600", color: C.textMuted, flexShrink: 1 },
    showLessText: { fontSize: 12, fontWeight: "600", color: C.textLight },
    evRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    evRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    evRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1 },
    evRsvpTextGoing: { color: C.primary },

    poll: {},

    // Hero card (dark bg — image overlay, intentional)
    heroCard: { marginHorizontal: 14, backgroundColor: "#111", overflow: "hidden" },
    heroImageWrap: { height: 280, position: "relative" },
    heroImagePlaceholder: { ...StyleSheet.absoluteFillObject, backgroundColor: "#2a2a2a" },
    heroOverlay: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    heroTypeBadge: {
        position: "absolute",
        top: 12,
        left: 12,
        backgroundColor: C.primary,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    heroTypeBadgeText: { fontSize: 9, fontWeight: "800", color: "#fff", letterSpacing: 1.5, textTransform: "uppercase" },
    heroContent: { position: "absolute", bottom: 0, left: 0, right: 0, padding: 14, gap: 6 },
    heroHeadline: {
        fontSize: 22,
        fontWeight: "900",
        color: "#fff",
        lineHeight: 27,
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },
    heroExcerpt: { fontSize: 13, color: "rgba(255,255,255,0.72)", lineHeight: 18 },
    heroRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 12,
        paddingVertical: 7,
        alignSelf: "flex-start",
    },
    heroRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: "rgba(255,255,255,0.5)" },
    heroRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1, textTransform: "uppercase" },
    heroStats: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 2 },
    heroStatText: { fontSize: 10, fontWeight: "600", color: "rgba(255,255,255,0.65)", letterSpacing: 0.5, textTransform: "uppercase" },
    heroStatDot: { fontSize: 10, color: "rgba(255,255,255,0.4)" },
    heroClubRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: "#1a1a1a",
    },
    heroClubAvatar: { width: 24, height: 24, borderRadius: 12, overflow: "hidden" },
    heroClubAvatarPlaceholder: { backgroundColor: C.primaryBg, alignItems: "center", justifyContent: "center" },
    heroClubName: { fontSize: 11, fontWeight: "700", color: "rgba(255,255,255,0.65)", textTransform: "uppercase", letterSpacing: 0.8 },

    // Text article card
    articleCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
    },
    cardBody: { paddingHorizontal: 16, paddingBottom: 14, gap: 6 },
    articleTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 2 },
    articleCategory: { fontSize: 10, fontWeight: "800", color: C.primary, letterSpacing: 1.5, textTransform: "uppercase" },
    articleHeadline: {
        fontSize: 18,
        fontWeight: "900",
        color: C.text,
        lineHeight: 23,
        textTransform: "uppercase",
        letterSpacing: 0.2,
    },
    articleExcerpt: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    articleByline: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 8,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    articleByText: { fontSize: 10, fontWeight: "700", color: C.textLight, letterSpacing: 0.8, textTransform: "uppercase" },
    articleByRight: { flexDirection: "row", alignItems: "center", gap: 14 },
    articleAction: { flexDirection: "row", alignItems: "center", gap: 4 },
    articleActionText: { fontSize: 12, fontWeight: "600", color: C.textLight },
    articleActionTextActive: { color: C.primary },
    articleByTime: { fontSize: 10, color: C.textLight, textTransform: "uppercase", letterSpacing: 0.5 },

    pollCardByline: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(255,255,255,0.15)",
    },
    pollCardByTime: { fontSize: 10, color: "rgba(255,255,255,0.45)", textTransform: "uppercase", letterSpacing: 0.5 },
    doubleTapHeart: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        alignItems: "center",
        justifyContent: "center",
    },

    // Image article card
    imgArticleCard: { backgroundColor: C.surface, overflow: "hidden", borderBottomWidth: 1, borderBottomColor: C.borderWarm },
    imgArticleImage: { width: "100%", aspectRatio: 1, backgroundColor: C.borderWarm },
    imgArticleBody: { padding: 16, paddingTop: 14, gap: 5 },
    imgArticleCategory: { fontSize: 10, fontWeight: "800", color: C.primary, letterSpacing: 1.5, textTransform: "uppercase" },
    imgArticleHeadline: {
        fontSize: 20,
        fontWeight: "900",
        color: C.text,
        lineHeight: 25,
        textTransform: "uppercase",
        letterSpacing: 0.2,
    },
    imgArticleExcerpt: { fontSize: 13, color: C.textMuted, lineHeight: 19 },
    imgArticleActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
        marginTop: 8,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    imgArticleRsvpBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        backgroundColor: C.primary,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    imgArticleRsvpBtnGoing: { backgroundColor: "transparent", borderWidth: 1.5, borderColor: C.primary },
    imgArticleRsvpText: { fontSize: 10, fontWeight: "800", color: "#fff", letterSpacing: 1, textTransform: "uppercase" },
    imgArticleRsvpTextGoing: { color: C.primary },
    imgArticleSaveBtn: { flexDirection: "row", alignItems: "center", gap: 5 },
    imgArticleActionText: { fontSize: 10, fontWeight: "700", color: C.textLight, letterSpacing: 0.8, textTransform: "uppercase" },

    // ── Announcement card ──────────────────────────────────────────────────
    announcementCard: {
        backgroundColor: C.surface,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        overflow: "hidden",
    },
    announcementInner: {
        flexDirection: "row",
    },
    announcementBorder: {
        width: 3,
        backgroundColor: C.primary,
    },
    announcementContent: {
        flex: 1,
        padding: 16,
        paddingTop: 14,
        gap: 6,
    },
    announcementHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 8,
    },
    announcementClubName: {
        fontSize: 13,
        fontWeight: "700",
        color: C.text,
    },
    announcementTypePill: {
        alignSelf: "flex-start",
        backgroundColor: C.primaryBg,
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 3,
        marginTop: 3,
    },
    announcementTypePillText: {
        fontSize: 9,
        fontWeight: "800",
        color: C.primary,
        letterSpacing: 1.2,
        textTransform: "uppercase",
    },
    announcementTimestamp: {
        fontSize: 10,
        color: C.textLight,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    announcementTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: C.text,
        lineHeight: 23,
        letterSpacing: -0.2,
    },
    announcementExcerpt: {
        fontSize: 13,
        color: C.textMuted,
        lineHeight: 20,
    },
    announcementImage: {
        width: "100%",
        height: 200,
        backgroundColor: C.borderWarm,
    },
    announcementActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 18,
        paddingHorizontal: 16,
        paddingVertical: 11,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: C.borderWarm,
    },
    announcementActionBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    announcementActionText: {
        fontSize: 12,
        fontWeight: "600",
        color: C.textLight,
    },
    announcementActionTextActive: { color: C.primary },
    announcementActionSpacer: { flex: 1 },

    multiImgPill: {
        position: "absolute",
        bottom: 8,
        right: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        backgroundColor: "rgba(0,0,0,0.55)",
        paddingHorizontal: 7,
        paddingVertical: 4,
        borderRadius: 4,
    },
    multiImgPillText: { fontSize: 11, fontWeight: "700", color: "#fff" },
});

export const styles = makeFeedStyles({
    bg: "#F7F3EE", surface: "#FFFFFF", surfaceAlt: "#F9FAFB", surfaceWarm: "#FAF6EF", loadingBg: "#D0D0D0",
    text: "#111827", textBody: "#374151", textMuted: "#6B7280", textLight: "#9CA3AF",
    textFaint: "#D1CBC3", primary: "#8C0327", primaryBg: "#FEE2E2", gold: "#A8763E",
    border: "#E5E7EB", borderWarm: "#E5E0D8", skeleton: "#E5E0D8",
    overlay: "rgba(0,0,0,0.5)",
});
