import { StyleSheet } from "react-native";
import type { AppColors } from "./theme";

export const makeHomeStyles = (C: AppColors) => StyleSheet.create({
    safe: { flex: 1, backgroundColor: C.bg },
    masthead: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 20,
        backgroundColor: C.bg,
    },
    mastheadTopRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 8,
        backgroundColor: C.bg,
    },
    mastheadScrollable: {
        paddingHorizontal: 20,
        paddingTop: 6,
        paddingBottom: 20,
        backgroundColor: C.bg,
    },
    mastheadLabel: {
        fontSize: 10,
        fontWeight: "800",
        color: C.primary,
        letterSpacing: 2,
    },
    mastheadActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
    },
    mastheadIconBtn: {
        position: "relative",
    },
    mastheadHeading: {
        fontSize: 42,
        fontWeight: "900",
        color: C.text,
        letterSpacing: -1,
        lineHeight: 46,
    },
    mastheadAccent: {
        width: 48,
        height: 3,
        backgroundColor: C.primary,
        marginTop: 12,
    },
    mastheadCenter: {
        flex: 1,
        alignItems: "center",
    },
    mastheadTitle: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 3,
        color: C.text,
        textTransform: "uppercase",
    },
    mastheadSide: {
        width: 28,
        alignItems: "center",
        position: "relative",
    },
    container: {
        gap: 0,
        flexGrow: 0,
    },
    feedSection: {
        paddingHorizontal: 0,
        paddingTop: 16,
        gap: 1,
    },
    feedHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingBottom: 12,
    },
    mastheadGreeting: {
        fontSize: 13,
        fontWeight: "700",
        color: C.text,
        letterSpacing: 0.2,
    },
    notifBadge: {
        position: "absolute",
        top: -2,
        right: -2,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: C.primary,
        borderWidth: 1.5,
        borderColor: C.bg,
    },
    feedHeaderTitle: {
        fontSize: 11,
        fontWeight: "800",
        letterSpacing: 1.5,
        color: C.textMuted,
        textTransform: "uppercase",
    },
    caughtUp: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 24,
        paddingVertical: 32,
        gap: 12,
    },
    caughtUpLine: {
        flex: 1,
        height: StyleSheet.hairlineWidth,
        backgroundColor: C.textFaint,
    },
    caughtUpText: {
        fontSize: 10,
        fontWeight: "800",
        color: C.textFaint,
        letterSpacing: 1.5,
    },
    discoverHeader: {
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 20,
    },
    discoverLabel: {
        fontSize: 10,
        fontWeight: "800",
        color: C.primary,
        letterSpacing: 2,
        marginBottom: 6,
    },
    discoverHeading: {
        fontSize: 42,
        fontWeight: "900",
        color: C.text,
        letterSpacing: -1,
        lineHeight: 46,
    },
    discoverAccent: {
        width: 48,
        height: 3,
        backgroundColor: C.primary,
        marginTop: 12,
    },
    emptyState: {
        alignItems: "center",
        paddingTop: 80,
        paddingHorizontal: 32,
        gap: 10,
    },
    emptyTitle: {
        fontSize: 13,
        fontWeight: "900",
        color: C.textFaint,
        letterSpacing: 2,
        marginTop: 8,
    },
    emptySubtitle: {
        fontSize: 13,
        color: C.textLight,
        textAlign: "center",
    },
    tabBar: {
        flexDirection: "row",
        backgroundColor: C.bg,
        borderBottomWidth: 1,
        borderBottomColor: C.borderWarm,
        position: "relative",
    },
    tab: {
        flex: 1,
        paddingVertical: 14,
        alignItems: "center",
        gap: 2,
    },
    tabActive: {},
    tabText: {
        fontSize: 13,
        fontWeight: "500",
        color: C.textLight,
        letterSpacing: 0.5,
    },
    tabTextActive: {
        fontSize: 13,
        fontWeight: "900",
        color: C.text,
        letterSpacing: -0.2,
    },
    tabIndicator: {
        position: "absolute",
        bottom: 0,
        left: 0,
        width: "50%",
        height: 2,
        backgroundColor: C.primary,
    },
    discoverBtn: {
        marginTop: 16,
        backgroundColor: C.primary,
        paddingHorizontal: 24,
        paddingVertical: 12,
    },
    discoverBtnText: {
        fontSize: 11,
        fontWeight: "800",
        color: "#fff",
        letterSpacing: 1.5,
    },
});

// Legacy alias kept for any imports that destructure { homeStyles }
export const homeStyles = makeHomeStyles({
    bg: "#F7F3EE", surface: "#FFFFFF", surfaceAlt: "#F9FAFB", loadingBg: "#D0D0D0",
    text: "#111827", textBody: "#374151", textMuted: "#6B7280", textLight: "#9CA3AF",
    textFaint: "#D1CBC3", primary: "#8C0327", primaryBg: "#FEE2E2", gold: "#A8763E",
    border: "#E5E7EB", borderWarm: "#E5E0D8", skeleton: "#E5E0D8",
    overlay: "rgba(0,0,0,0.5)",
});
